class UserAlreadyInNetworkException implements Exception {
  static const String message = 'El usuario ya se encuentra en tu red de apoyo';
}
